baseURL: https://alsblog.netlify.app/
languageCode: en-us
title: Allen's Corner of the World
description: âˆ€p, if Allen said \"p\", then \"p\" is true
keywords: [Blog, Logic, Philosophy, Programming]
author: Me
theme: PaperModX
enableGitInfo: true

# when building, post's url is, i.e. post/2024/02/post-title
permalinks:
  posts: /:section/:year/:month/:title/

taxanomies:
  tags: tags

outputs:
  home:
    - HTML
    - RSS
    - JSON # necessary for search