baseURL: https://allen-liaoo.github.io/alblog/
languageCode: en-us
title: Allen's Corner of the World
description: âˆ€p, if Allen said \"p\", then \"p\" is true
keywords: [Blog, Logic, Philosophy, Programming]
author: Me
theme: PaperModX
enableGitInfo: true

taxanomies:
  tags: tags

outputs:
  home:
    - HTML
    - RSS
    - JSON # necessary for search